# Convert the exr depth file generated by nvisii_mvs into npz file 
# These are range depth map 

import json
import math
import subprocess
import argparse
import cv2
import glob
import numpy as np
import pyexr
parser = argparse.ArgumentParser()

parser.add_argument(
    '--path', 
    type = str, 
    default = None,
    required = True,
)
parser.add_argument(
    '--compressed', 
    action = "store_true",
    help = 'compressed the output'
)
parser.add_argument(
    '--delete', 
    action = "store_true",
    help = 'Delete the exr file'
)
opt = parser.parse_args()

depth_exr_files = sorted(glob.glob(opt.path+"*.depth.exr"))

for file in depth_exr_files:
    img_depth_range = cv2.imread(file,  
                        cv2.IMREAD_ANYCOLOR | cv2.IMREAD_ANYDEPTH) 
    img_depth_range[img_depth_range<-3.4028235e+37] = img_depth_range.max()
    img_depth_range[img_depth_range>3.4028235e+37] = img_depth_range.min()
    img_depth_range = img_depth_range[:,:,0]
    if opt.compressed: 
        np.savez_compressed(file.replace("exr","npz"),img_depth_range)
    else:
        np.savez(file.replace("exr","npz"),img_depth_range)
    
    if opt.delete:
        subprocess.call(["rm",file])